name: Build/Test

on: [ push, pull_request ]

jobs:
  build:
    name: build/test on node versions

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # 2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            nodejs.org:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # 4.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn type-check
      - run: yarn lint
      - run: yarn lint-tests
      - run: yarn build
      - run: yarn test
