name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # 2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # 3.3.0
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # 3.6.0
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@4223352d770913cb84156b647ff08e7dcaba1028 # 3.2
        id: semantic
        with:
          semantic_version: 19.0.2
          branch: main
          extends: |
            @rweich/semantic-release-config
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo release version: ${{ steps.semantic.outputs.new_release_version }}
